//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameOfLife.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameOfLife.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Game of Life.
        /// </summary>
        internal static string appendTitle {
            get {
                return ResourceManager.GetString("appendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // .
        /// </summary>
        internal static string commentPrefix {
            get {
                return ResourceManager.GetString("commentPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cursorIcon {
            get {
                object obj = ResourceManager.GetObject("cursorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  = .
        /// </summary>
        internal static string equalSign {
            get {
                return ResourceManager.GetString("equalSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eraser {
            get {
                object obj = ResourceManager.GetObject("eraser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon eraser1 {
            get {
                object obj = ResourceManager.GetObject("eraser1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eraserIcon {
            get {
                object obj = ResourceManager.GetObject("eraserIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New World.
        /// </summary>
        internal static string fileNewWorld {
            get {
                return ResourceManager.GetString("fileNewWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finite.
        /// </summary>
        internal static string finite {
            get {
                return ResourceManager.GetString("finite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gameOfLifeIcon {
            get {
                object obj = ResourceManager.GetObject("gameOfLifeIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap goIcon {
            get {
                object obj = ResourceManager.GetObject("goIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap importIcon {
            get {
                object obj = ResourceManager.GetObject("importIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Color.
        /// </summary>
        internal static string labelBackColor {
            get {
                return ResourceManager.GetString("labelBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string labelBoundary {
            get {
                return ResourceManager.GetString("labelBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Color.
        /// </summary>
        internal static string labelCellColor {
            get {
                return ResourceManager.GetString("labelCellColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alive.
        /// </summary>
        internal static string labelCellCount {
            get {
                return ResourceManager.GetString("labelCellCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Count.
        /// </summary>
        internal static string labelColumnCount {
            get {
                return ResourceManager.GetString("labelColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Grid.
        /// </summary>
        internal static string labelDisplayGrid {
            get {
                return ResourceManager.GetString("labelDisplayGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display HUD.
        /// </summary>
        internal static string labelDisplayHUD {
            get {
                return ResourceManager.GetString("labelDisplayHUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Neighbor Count.
        /// </summary>
        internal static string labelDisplayNeighborCount {
            get {
                return ResourceManager.GetString("labelDisplayNeighborCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generations.
        /// </summary>
        internal static string labelGenerations {
            get {
                return ResourceManager.GetString("labelGenerations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Color.
        /// </summary>
        internal static string labelGridColor {
            get {
                return ResourceManager.GetString("labelGridColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid x10 Color.
        /// </summary>
        internal static string labelGridx10Color {
            get {
                return ResourceManager.GetString("labelGridx10Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        internal static string labelInterval {
            get {
                return ResourceManager.GetString("labelInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Count.
        /// </summary>
        internal static string labelRowCount {
            get {
                return ResourceManager.GetString("labelRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed.
        /// </summary>
        internal static string labelSeed {
            get {
                return ResourceManager.GetString("labelSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string labelTextNA {
            get {
                return ResourceManager.GetString("labelTextNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string labelUniverseSize {
            get {
                return ResourceManager.GetString("labelUniverseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newIcon {
            get {
                object obj = ResourceManager.GetObject("newIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nextIcon {
            get {
                object obj = ResourceManager.GetObject("nextIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paintIcon {
            get {
                object obj = ResourceManager.GetObject("paintIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pauseIcon {
            get {
                object obj = ResourceManager.GetObject("pauseIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap randomizeIcon {
            get {
                object obj = ResourceManager.GetObject("randomizeIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reloadIcon {
            get {
                object obj = ResourceManager.GetObject("reloadIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a seed....
        /// </summary>
        internal static string seedPrompt {
            get {
                return ResourceManager.GetString("seedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.cfg.
        /// </summary>
        internal static string settingsFile {
            get {
                return ResourceManager.GetString("settingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to old_settings.cfg.
        /// </summary>
        internal static string settingsPrevious {
            get {
                return ResourceManager.GetString("settingsPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap startIcon {
            get {
                object obj = ResourceManager.GetObject("startIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torodial.
        /// </summary>
        internal static string torodial {
            get {
                return ResourceManager.GetString("torodial", resourceCulture);
            }
        }
    }
}
